paths:
    jquery: "libs/jquery/jquery-min"
    livequery: "libs/jquery/livequery"
    timeago: "libs/jquery/jquery-timeago"
    rails: "libs/jquery/rails"
    underscore: "libs/underscore/underscore-min"
    backbone: "libs/backbone/backbone-optamd3-min"
    modelbinding: "libs/backbone/backbone.modelbinding"
    bootstrap: "libs/twitter/bootstrap"
    handlebars: "libs/handlebars/handlebars.1.0.0.beta.3"
    viewporter: "libs/zynga/viewporter"
    text: "libs/require/text"
    iscroll: "libs/iscroll/iscroll"
    application: "application"
    juggernaut: "http://2012itforum.lfg.com:8080/application"

modules:
  - name: "jquery"
  - name: "livequery"
  - name: "timeago"
  - name: "rails"
  - name: "underscore"
  - name: "backbone"
  - name: "modelbinding"
  - name: "bootstrap"
  - name: "handlebars"
  - name: "viewporter"
  - name: "text"
  - name: "iscroll"
  - name: "application"
  - name: "juggernaut"

priority: ['jquery']